# Generated by Django 4.0.2 on 2022-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='picture',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
