# Generated by Django 4.0.2 on 2022-03-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0002_card_picture_alter_card_name_alter_card_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
