# Generated by Django 4.0.2 on 2022-03-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0003_name_alter_card_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='card',
            name='healthy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='legend_shop_main.healthy'),
        ),
    ]
