# Generated by Django 4.0.2 on 2022-03-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0004_healthy_alter_card_options_alter_name_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='healthy',
            options={'verbose_name': 'Полезность', 'verbose_name_plural': 'Полезности'},
        ),
    ]
