# Generated by Django 4.0.2 on 2022-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0006_card_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
