# Generated by Django 4.0.2 on 2022-04-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0007_card_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Healthy',
            new_name='Usefulness',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
