# Generated by Django 4.0.2 on 2022-04-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend_shop_main', '0008_rename_healthy_usefulness_delete_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Product',
        ),
    ]
